#!/usr/bin/env python3
# Copyright (c) 2026 Justin Davis (davisjustin302@gmail.com)
#
# MIT License
"""Coverage ratcheting script -- validates coverage against thresholds.

Reads an existing .coverage.json report (generated by ``make test-cov``)
and checks per-module branch coverage against recorded thresholds.

This script does NOT run tests -- it only validates an existing report.
Run ``make test-cov`` first to generate .coverage.json.

Usage::

    python ci/check_coverage.py                    # Check mode (read-only)
    python ci/check_coverage.py --update           # Ratchet thresholds up
    python ci/check_coverage.py --verbose          # Show per-module breakdown
    python ci/check_coverage.py --report FILE      # Use specific report file

Exit codes:
    0 -- All modules at or above threshold
    1 -- One or more modules below threshold
    2 -- Missing report file or threshold file
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

THRESHOLD_FILE = Path(__file__).resolve().parent.parent / ".coverage-threshold.json"
DEFAULT_REPORT = Path(__file__).resolve().parent.parent / ".coverage.json"

SRC_PREFIX = "src/"


def load_coverage_report(report_path: Path) -> dict:
    """Load and validate coverage JSON report."""
    if not report_path.exists():
        print(f"ERROR: Coverage report not found: {report_path}")
        print("Run `make test-cov` first to generate the report.")
        sys.exit(2)
    with report_path.open() as f:
        return json.load(f)


def _module_key(filepath: str) -> str | None:
    """Derive the module key from a coverage report filepath.

    Maps source paths to module keys used in ``.coverage-threshold.json``.

    Examples
    --------
    - ``src/trtutils/core/_memory.py``  -> ``trtutils/core``
    - ``src/trtutils/_engine.py``       -> ``trtutils/_engine``
    - ``src/trtutils/image/kernels.py`` -> ``trtutils/image``

    Returns ``None`` for paths that cannot be mapped (e.g. single-segment paths).
    """
    # Strip leading src/ prefix only
    rel = filepath[len(SRC_PREFIX) :] if filepath.startswith(SRC_PREFIX) else filepath
    parts = rel.split("/")

    if len(parts) >= 3:
        # e.g., trtutils/core/_memory.py -> trtutils/core
        return "/".join(parts[:2])
    if len(parts) == 2:
        # e.g., trtutils/_engine.py -> trtutils/_engine
        return parts[0] + "/" + Path(parts[1]).stem
    return None


def calculate_module_coverage(files: dict) -> dict[str, float]:
    """Calculate branch coverage percentage per module.

    Aggregates ``covered_branches / num_branches`` across all files in each
    module.  Uses slash-separated keys derived from file paths (e.g.,
    ``trtutils/core``).

    Weighting is by total branches, not by file count -- a 200-branch file
    contributes more than a 10-branch file within the same module.
    """
    module_stats: dict[str, dict[str, int]] = {}

    for filepath, data in files.items():
        module = _module_key(filepath)
        if module is None:
            continue

        if module not in module_stats:
            module_stats[module] = {"covered": 0, "total": 0}

        summary = data.get("summary", {})
        module_stats[module]["covered"] += summary.get("covered_branches", 0)
        module_stats[module]["total"] += summary.get("num_branches", 0)

    return {
        mod: (s["covered"] / s["total"] * 100.0 if s["total"] > 0 else 100.0)
        for mod, s in module_stats.items()
    }


def _print_help() -> None:
    """Print usage information."""
    print(__doc__)


def main() -> int:
    """Run coverage check or update thresholds."""
    if "--help" in sys.argv or "-h" in sys.argv:
        _print_help()
        return 0

    update_mode = "--update" in sys.argv
    verbose = "--verbose" in sys.argv

    # Find report file
    report_path = DEFAULT_REPORT
    if "--report" in sys.argv:
        idx = sys.argv.index("--report")
        if idx + 1 < len(sys.argv):
            report_path = Path(sys.argv[idx + 1])
        else:
            print("ERROR: --report requires a file path argument")
            return 2

    # Load threshold file
    if not THRESHOLD_FILE.exists():
        print(f"ERROR: Threshold file not found: {THRESHOLD_FILE}")
        return 2
    with THRESHOLD_FILE.open() as f:
        thresholds: dict[str, float] = json.load(f)

    # Load and parse coverage report
    cov_data = load_coverage_report(report_path)
    coverage = calculate_module_coverage(cov_data.get("files", {}))

    if verbose:
        print("\n--- Per-Module Branch Coverage ---")
        for mod, pct_raw in sorted(coverage.items()):
            pct = round(pct_raw, 1)
            threshold = thresholds.get(mod)
            marker = ""
            if threshold is not None:
                if pct < threshold:
                    marker = " [BELOW THRESHOLD]"
                elif pct > threshold:
                    marker = " [ABOVE THRESHOLD]"
            print(f"  {mod}: {pct:.1f}%{marker}")
        print()

    # Warn about modules in coverage report but not in threshold file
    new_modules = sorted(mod for mod in coverage if mod not in thresholds)
    for mod in new_modules:
        print(f"WARN: {mod} found in coverage but not in threshold file")
        if update_mode:
            # Add new modules at their current coverage level
            rounded = round(coverage[mod], 1)
            thresholds[mod] = rounded
            print(f"  -> Added to thresholds at {rounded:.1f}%")

    # Check each threshold
    # Round current values to 1 decimal place before comparing -- thresholds
    # are stored at this precision, so raw floats must match to avoid false
    # failures from floating-point rounding (e.g., 66.667% vs stored 66.7).
    failed = False
    for module, threshold in sorted(thresholds.items()):
        current_raw = coverage.get(module, 0.0)
        current = round(current_raw, 1)
        if current < threshold:
            print(f"FAIL: {module} coverage {current:.1f}% < threshold {threshold:.1f}%")
            failed = True
        elif current > threshold:
            print(f"UP:   {module} {threshold:.1f}% -> {current:.1f}%")
            if update_mode:
                # Ratchet only goes UP -- never lower a threshold
                thresholds[module] = current
        else:
            print(f"OK:   {module} at {current:.1f}%")

    # Write threshold file only in update mode
    if update_mode:
        # Sort keys for stable output
        sorted_thresholds = dict(sorted(thresholds.items()))
        with THRESHOLD_FILE.open("w") as f:
            json.dump(sorted_thresholds, f, indent=4)
            f.write("\n")
        print("\nThresholds updated.")

    if failed:
        print("\nCoverage check FAILED. Run tests to improve coverage.")
        return 1

    print("\nCoverage check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
