#!/usr/bin/env python3
# Copyright (c) 2024 Justin Davis (davisjustin302@gmail.com)
#
# MIT License
"""
Coverage ratcheting script — validates coverage against thresholds.

Reads an existing .coverage.json report (generated by `make test-cov`)
and checks per-module branch coverage against recorded thresholds.

This script does NOT run tests — it only validates an existing report.
Run `make test-cov` first to generate .coverage.json.

Usage:
    python ci/check_coverage.py                    # Check mode (read-only)
    python ci/check_coverage.py --update           # Update thresholds to current values
    python ci/check_coverage.py --verbose          # Show per-file breakdown
    python ci/check_coverage.py --report FILE      # Use specific report file

Exit codes:
    0 — All modules at or above threshold
    1 — One or more modules below threshold
    2 — Missing report file or threshold file
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

THRESHOLD_FILE = Path(__file__).parent.parent / ".coverage-threshold.json"
DEFAULT_REPORT = Path(__file__).parent.parent / ".coverage.json"


def load_coverage_report(report_path: Path) -> dict:
    """Load and validate coverage JSON report."""
    if not report_path.exists():
        print(f"ERROR: Coverage report not found: {report_path}")
        print("Run `make test-cov` first to generate the report.")
        sys.exit(2)
    return json.loads(report_path.read_text())


def calculate_module_coverage(files: dict) -> dict[str, float]:
    """
    Calculate branch coverage percentage per module.

    Aggregates covered_branches / num_branches across all files in each module.
    Uses slash-separated keys derived from file paths (e.g., ``trtutils/core``).
    """
    module_stats: dict[str, dict[str, int]] = {}

    for filepath, data in files.items():
        # Strip src/ prefix: src/trtutils/core/_memory.py -> trtutils/core/_memory.py
        rel = filepath.replace("src/", "")
        parts = rel.split("/")

        # Determine module key
        if len(parts) >= 3:
            # e.g., trtutils/core/_memory.py -> trtutils/core
            module = "/".join(parts[:2])
        elif len(parts) == 2:
            # e.g., trtutils/_engine.py -> trtutils/_engine
            module = parts[0] + "/" + Path(parts[1]).stem
        else:
            continue

        if module not in module_stats:
            module_stats[module] = {"covered": 0, "total": 0}

        summary = data["summary"]
        module_stats[module]["covered"] += summary.get("covered_branches", 0)
        module_stats[module]["total"] += summary.get("num_branches", 0)

    return {
        mod: (s["covered"] / s["total"] * 100 if s["total"] > 0 else 100.0)
        for mod, s in module_stats.items()
    }


def main() -> int:
    """Run coverage check or update thresholds."""
    update_mode = "--update" in sys.argv
    verbose = "--verbose" in sys.argv

    # Find report file
    report_path = DEFAULT_REPORT
    if "--report" in sys.argv:
        idx = sys.argv.index("--report")
        if idx + 1 < len(sys.argv):
            report_path = Path(sys.argv[idx + 1])

    # Load threshold file
    if not THRESHOLD_FILE.exists():
        print(f"ERROR: Threshold file not found: {THRESHOLD_FILE}")
        sys.exit(2)
    thresholds = json.loads(THRESHOLD_FILE.read_text())

    # Load and parse coverage report
    cov_data = load_coverage_report(report_path)
    coverage = calculate_module_coverage(cov_data.get("files", {}))

    if verbose:
        print("\n--- Per-Module Coverage ---")
        for mod, pct in sorted(coverage.items()):
            print(f"  {mod}: {pct:.1f}%")
        print()

    # Warn about modules in coverage report but not in threshold file
    for mod in sorted(coverage.keys()):
        if mod not in thresholds:
            print(f"WARN: {mod} found in coverage but not in threshold file")

    failed = False
    for module, threshold in sorted(thresholds.items()):
        current = coverage.get(module, 0.0)
        if current < threshold:
            print(f"FAIL: {module} coverage {current:.1f}% < threshold {threshold:.1f}%")
            failed = True
        elif current > threshold:
            print(f"UP:   {module} {threshold:.1f}% -> {current:.1f}%")
            if update_mode:
                thresholds[module] = round(current, 1)
        else:
            print(f"OK:   {module} at {current:.1f}%")

    # Only write threshold file in update mode
    if update_mode:
        THRESHOLD_FILE.write_text(json.dumps(thresholds, indent=4) + "\n")
        print("\nThresholds updated.")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
