"""
This type stub file was generated by pyright.
"""

from pycuda.tools import context_dependent_memoize

"""
This type stub file was generated by pyright.
"""
def platform_bits():
    ...

def has_stack():
    ...

def has_double_support():
    ...

@context_dependent_memoize
def sizeof(type_name, preamble=...):
    ...

