"""
This type stub file was generated by pyright.
"""

from pycuda.tools import context_dependent_memoize

def platform_bits(): # -> Literal[64, 32]:
    ...

def has_stack():
    ...

def has_double_support():
    ...

@context_dependent_memoize
def sizeof(type_name, preamble=...): # -> int:
    ...

