"""
This type stub file was generated by pyright.
"""

from pytools import memoize

"""
This type stub file was generated by pyright.
"""
@memoize
def get_nvcc_version(nvcc):
    ...

def preprocess_source(source, options, nvcc):
    ...

def compile_plain(source, options, keep, nvcc, cache_dir, target=...):
    ...

DEFAULT_NVCC_FLAGS = ...
def compile(source, nvcc=..., options=..., keep=..., no_extern_c=..., arch=..., code=..., cache_dir=..., include_dirs=..., target=...):
    ...

class CudaModule:
    def get_function(self, name):
        ...
    


class SourceModule(CudaModule):
    """
    Creates a Module from a single .cu source object linked against the
    static CUDA runtime.
    """
    def __init__(self, source, nvcc=..., options=..., keep=..., no_extern_c=..., arch=..., code=..., cache_dir=..., include_dirs=...) -> None:
        ...
    


class DynamicModule(CudaModule):
    """
    Creates a Module from multiple .cu source, library file and/or data
    objects linked against the static or dynamic CUDA runtime.
    """
    def __init__(self, nvcc=..., link_options=..., keep=..., no_extern_c=..., arch=..., code=..., cache_dir=..., include_dirs=..., message_handler=..., log_verbose=..., cuda_libdir=...) -> None:
        ...
    
    def add_source(self, source, nvcc_options=..., name=...):
        ...
    
    def add_data(self, data, input_type, name=...):
        ...
    
    def add_file(self, filename, input_type):
        ...
    
    def add_stdlib(self, libname):
        ...
    
    def link(self):
        ...
    


class DynamicSourceModule(DynamicModule):
    """
    Creates a Module from a single .cu source object linked against the
    dynamic CUDA runtime.
    - compiler generates PTX relocatable device code (rdc) from source that
      can be linked with other relocatable device code
    - source is linked against the CUDA device runtime library cudadevrt
    - library cudadevrt is statically linked into the generated Module
    """
    def __init__(self, source, nvcc=..., options=..., keep=..., no_extern_c=..., arch=..., code=..., cache_dir=..., include_dirs=..., cuda_libdir=...) -> None:
        ...
    


