"""
This type stub file was generated by pyright.
"""

from os.path import exists

"""
This type stub file was generated by pyright.
"""
parser = ...
if len(args) < 1:
    ...
mainpyfile = ...
if not exists(mainpyfile):
    ...
