"""
This type stub file was generated by pyright.
"""

from pycuda.tools import context_dependent_memoize

"""Computation of reductions on vectors."""
__copyright__ = ...
__license__ = ...
def get_reduction_module(out_type, block_size, neutral, reduce_expr, map_expr, arguments, name=..., keep=..., options=..., preamble=...): # -> SourceModule:
    ...

def get_reduction_kernel_and_types(stage, out_type, block_size, neutral, reduce_expr, map_expr=..., arguments=..., name=..., keep=..., options=..., preamble=...): # -> tuple[Any, list[str]]:
    ...

class ReductionKernel:
    def __init__(self, dtype_out, neutral, reduce_expr, map_expr=..., arguments=..., name=..., keep=..., options=..., preamble=...) -> None:
        ...
    
    def __call__(self, *args, **kwargs): # -> empty:
        ...
    


@context_dependent_memoize
def get_sum_kernel(dtype_out, dtype_in): # -> ReductionKernel:
    ...

@context_dependent_memoize
def get_any_kernel(dtype_out, dtype_in): # -> ReductionKernel:
    ...

@context_dependent_memoize
def get_all_kernel(dtype_out, dtype_in): # -> ReductionKernel:
    ...

@context_dependent_memoize
def get_subset_sum_kernel(dtype_out, dtype_subset, dtype_in): # -> ReductionKernel:
    ...

@context_dependent_memoize
def get_dot_kernel(dtype_out, dtype_a, dtype_b): # -> ReductionKernel:
    ...

@context_dependent_memoize
def get_subset_dot_kernel(dtype_out, dtype_subset, dtype_a=..., dtype_b=...): # -> ReductionKernel:
    ...

def get_minmax_neutral(what, dtype): # -> str:
    ...

@context_dependent_memoize
def get_minmax_kernel(what, dtype): # -> ReductionKernel:
    ...

@context_dependent_memoize
def get_subset_minmax_kernel(what, dtype, dtype_subset): # -> ReductionKernel:
    ...

