"""
This type stub file was generated by pyright.
"""

from pycuda.tools import context_dependent_memoize

"""
This type stub file was generated by pyright.
"""
__copyright__ = ...
__license__ = ...
def get_reduction_module(out_type, block_size, neutral, reduce_expr, map_expr, arguments, name=..., keep=..., options=..., preamble=...):
    ...

def get_reduction_kernel_and_types(stage, out_type, block_size, neutral, reduce_expr, map_expr=..., arguments=..., name=..., keep=..., options=..., preamble=...):
    ...

class ReductionKernel:
    def __init__(self, dtype_out, neutral, reduce_expr, map_expr=..., arguments=..., name=..., keep=..., options=..., preamble=...) -> None:
        ...
    
    def __call__(self, *args, **kwargs):
        ...
    


@context_dependent_memoize
def get_sum_kernel(dtype_out, dtype_in):
    ...

@context_dependent_memoize
def get_any_kernel(dtype_out, dtype_in):
    ...

@context_dependent_memoize
def get_all_kernel(dtype_out, dtype_in):
    ...

@context_dependent_memoize
def get_subset_sum_kernel(dtype_out, dtype_subset, dtype_in):
    ...

@context_dependent_memoize
def get_dot_kernel(dtype_out, dtype_a, dtype_b):
    ...

@context_dependent_memoize
def get_subset_dot_kernel(dtype_out, dtype_subset, dtype_a=..., dtype_b=...):
    ...

def get_minmax_neutral(what, dtype):
    ...

@context_dependent_memoize
def get_minmax_kernel(what, dtype):
    ...

@context_dependent_memoize
def get_subset_minmax_kernel(what, dtype, dtype_subset):
    ...

