"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
__copyright__ = ...
__license__ = ...
bitlog2 = ...
DeviceMemoryPool = ...
PageLockedMemoryPool = ...
PageLockedAllocator = ...
class DebugMemoryPool(DeviceMemoryPool):
    def __init__(self, interactive=..., logfile=...) -> None:
        ...
    
    def allocate(self, size):
        ...
    
    def describe(self, stack, size):
        ...
    


def get_default_device(default=...):
    ...

def make_default_context(ctx_maker=...):
    ...

class DeviceData:
    def __init__(self, dev=...) -> None:
        ...
    
    def align(self, bytes, word_size=...):
        ...
    
    def align_dtype(self, elements, dtype_size):
        ...
    
    def align_words(self, word_size):
        ...
    
    def align_bytes(self, word_size=...):
        ...
    
    def coalesce(self, thread_count):
        ...
    
    @staticmethod
    def make_valid_tex_channel_count(size):
        ...
    


class OccupancyRecord:
    def __init__(self, devdata, threads, shared_mem=..., registers=...) -> None:
        ...
    


class Argument:
    def __init__(self, dtype, name) -> None:
        ...
    
    def __repr__(self):
        ...
    


def dtype_to_ctype(dtype, with_fp_tex_hack=...):
    ...

class VectorArg(Argument):
    def declarator(self):
        ...
    
    struct_char = ...


class ScalarArg(Argument):
    def declarator(self):
        ...
    
    @property
    def struct_char(self):
        ...
    


def parse_c_arg(c_arg):
    ...

def get_arg_type(c_arg):
    ...

context_dependent_memoized_functions = ...
def context_dependent_memoize(func):
    ...

def clear_context_caches():
    ...

def mark_cuda_test(inner_f):
    ...

def init_cuda_context_fixture():
    ...

