name: Ruff
on: [ push ]
jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install ruff
        run: pip install --upgrade ruff
      - name: Ruff Format Check
        run: ./ci/run_ruff.sh --format --check --diff

  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install ruff
        run: pip install --upgrade ruff
      - name: Ruff Check
        run: ./ci/run_ruff.sh --lint --no-fix
