name: Ruff - Examples
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check examples --ignore=INP001,T201"
