name: Ruff - Source
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v3
        with:
          src: src/trtutils
