name: Ruff - Tests
on: [ push ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check tests --ignore=S101,D100,D104,PLR2004"
